### ISSUE TITLE
It does not compile on mac osx with clang compiler

### ISSUE THREAD

**Issue by Arribas** [JamesTCurran/GNSS-Metadata-Standard#2]
MacBook-Pro-de-Javier:build javier$ make
[  4%] Built target xml
[  6%] Building CXX object API/source/lib/GnssMetadata/CMakeFiles/api.dir/Date.cpp.o
In file included from /Users/javier/gnss/GNSS-Metadata-Standard/API/source/lib/GnssMetadata/Date.cpp:22:
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/inc/GnssMetadata/Date.h:54:15: error: unknown type name 'IonTimespec'
                Date( const IonTimespec& tspec);
                            ^
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/inc/GnssMetadata/Date.h:75:3: error: unknown type name 'IonTimespec'
                IonTimespec SinceGps0() const; 
                ^
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/inc/GnssMetadata/Date.h:100:3: error: unknown type name 'IonTimespec'
                IonTimespec _dt;
                ^
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/lib/GnssMetadata/Date.cpp:111:19: error: unknown type name 'IonTimespec'
Date::Date( const IonTimespec& tspec)
                  ^
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/lib/GnssMetadata/Date.cpp:180:1: error: unknown type name 'IonTimespec'
IonTimespec Date::SinceGps0() const
^
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/lib/GnssMetadata/Date.cpp:182:2: error: unknown type name 'IonTimespec'
        IonTimespec gt = _dt; 
        ^
/Users/javier/gnss/GNSS-Metadata-Standard/API/source/lib/GnssMetadata/Date.cpp:192:2: error: unknown type name 'IonTimespec'
        IonTimespec gt = _dt; 
        ^
7 errors generated.
make[2]: *** [API/source/lib/GnssMetadata/CMakeFiles/api.dir/Date.cpp.o] Error 1
make[1]: *** [API/source/lib/GnssMetadata/CMakeFiles/api.dir/all] Error 2
make: *** [all] Error 2

**Comment by JamesTCurran** [comment]
Fixed (let me know if it's fixed for you too)

Compiles clean on Xcode and clang (make)
